spring: 
  profiles: 
    active: 
      - dev
---
spring: 
  profiles: dev           #开发环境
  application: 
    name: microservicecloud-config-aolc-dev
---
spring: 
  profiles: test           #测试环境
  application: 
    name: microservicecloud-config-aolc-test

#  注意：文件请保存为UTF-8格式
